import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'vault/.obsidian/plugins/hello-plugin/main.js',
	minify: prod,
});

const copyAssets = () => {
	fs.mkdirSync('vault/.obsidian/plugins/hello-plugin', { recursive: true });
	fs.copyFileSync('manifest.json', 'vault/.obsidian/plugins/hello-plugin/manifest.json');
};

if (prod) {
	await context.rebuild();
	copyAssets();
	process.exit(0);
} else {
	await context.rebuild();
	copyAssets();
	await context.watch();
}