import esbuild from 'esbuild';
import process from 'process';
import fs from 'node:fs';
import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outDir = prod ? 'dist' : 'vault/.obsidian/plugins/hello-plugin';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outDir}/main.js`,
	minify: prod,
});

const copyAssets = () => {
	fs.mkdirSync(outDir, { recursive: true });
	fs.copyFileSync('manifest.json', `${outDir}/manifest.json`);
	fs.copyFileSync('styles.css', `${outDir}/styles.css`);
};

if (prod) {
	await context.rebuild();
	copyAssets();
	process.exit(0);
} else {
	await context.rebuild();
	copyAssets();
	await context.watch();

	// also watch static assets in dev mode
	for (const asset of ['manifest.json', 'styles.css']) {
		fs.watch(asset, () => {
			fs.copyFileSync(asset, `${outDir}/${asset}`);
			console.log(`[watch] ${asset} → ${outDir}/`);
		});
	}
}
